/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mgarcia' at '10/21/14 5:35 PM' with Gradle 2.1
 *
 * @author mgarcia, @date 10/21/14 5:35 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
