keys-import: rake act:keys_import
file-monitor: rake act:file_monitor

resque: QUEUE=* bundle exec rake environment resque:work
resque-scheduler: bundle exec rake resque:scheduler
resque-web: bundle exec resque-web --foreground --no-launch