/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'mgarcia' at '10/21/14 5:35 PM' with Gradle 2.1
 *
 * @author mgarcia, @date 10/21/14 5:35 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
